### ISSUE TITLE
error looking for postgres

### ISSUE THREAD

**Issue by rburgst** [oznu/docker-unms#6]
When I launch the container, I get the following error in the `docker logs`

```
nc: bad address 'unms-postgres'
nc: bad address 'unms-postgres'
nc: bad address 'unms-postgres'
nc: bad address 'unms-postgres'
...
```

**Comment by oznu** [comment]
Hi @rburgst,

Can you show the command you are using to start `oznu/unms`?

My image does not do the `nc` checks on startup like the official image does so I'm not sure where this error would be coming from.

**Comment by rburgst** [comment]
Ok, I used synology docker to launch it and it somehow read the default environment values from the docker image and prepopulated PGHOST, etc.

Now I use your commandline and it works.

**Comment by joubin** [comment]
Hi @rburgst 

Can you share what you did? I'm having issues with the same error as you. Here is my `docker-compose`

```yml
version: '2'
services:
  unms:
    image: ubnt/unms
    restart: always
    ports:
      - 780:80
      - 7443:443
      - 2055:2055/udp
    environment:
      - TZ=Australia/Sydney
      - PUBLIC_HTTPS_PORT=7443
      - PUBLIC_WS_PORT=7443
    volumes:
      - ./volumes/unms:/config
```
